[font]
size = 13.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[colors.primary]
foreground = "#CDD6F4"
background = "#1E1E2E"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[cursor]
style = { shape = "Beam", blinking = "on" }

[window]
opacity = 0.7
