[[language]]
name = "php"
roots = ["composer.json", "index.php"]
file-types = ["php", "blade"]
formatter = { command = "php-cs-fixer", args = [
    "fix",
    "--using-cache=no",
    "/dev/stdin",
] }
auto-format = true
diagnostic-severity = "error"
