[default_session]

[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "vim"

[[session]]
name = "Work"
path = "~/Documents/Work"

[[session]]
name = "Learning"
path = "~/learning"

[[session]]
name = "Hermes Updates"
path = "~/Documents/School/Year4/Stage/Examen 1/cerberos-hermes-updates"
