[default_session]

[[session]]
name = "Dotfiles"
path = "~/dotfiles"
startup_command = "vim"

[[session]]
name = "Work"
path = "~/projects/work"

[[session]]
name = "Nvim Config"
path = "~/dotfiles/nvim"
startup_command = "vim"

[[session]]
name = "Hermes Updates"
path = "~/projects/school/cerberos-hermes-updates"
